"""removed languages

Revision ID: 9d2907e47fac
Revises: 2505c8c83559
Create Date: 2021-07-15 00:15:47.911737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d2907e47fac'
down_revision = '2505c8c83559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'language')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('language', sa.VARCHAR(length=5), nullable=True))
    # ### end Alembic commands ###
